package com.fajarnuha.kson

import kotlin.properties.ReadWriteProperty
import kotlin.reflect.KProperty

/**
 * Stores one property of a builder generated by kson-ksp for a [Kson] interface.
 * Reading a property that has no default before it is set throws [IllegalStateException].
 */
public class KsonProperty<T> private constructor(
    private val owner: String,
    private var value: Any?,
    private var isSet: Boolean,
) : ReadWriteProperty<Any?, T> {
    /** A required property. [owner] names the interface in error messages. */
    public constructor(owner: String) : this(owner, null, false)

    /** An optional property that starts as [default]. */
    public constructor(owner: String, default: T) : this(owner, default, true)

    override fun getValue(thisRef: Any?, property: KProperty<*>): T {
        check(isSet) { "$owner.${property.name} is not set" }
        @Suppress("UNCHECKED_CAST")
        return value as T
    }

    override fun setValue(thisRef: Any?, property: KProperty<*>, value: T) {
        this.value = value
        isSet = true
    }
}

/** Collects the items of a `List` property in a builder generated by kson-ksp. */
@JsonDsl
public class KsonListBuilder<T, B>(
    private val newBuilder: () -> B,
    private val build: (B) -> T,
) {
    private val items = mutableListOf<T>()

    /** Adds an existing value. */
    public fun add(value: T) {
        items += value
    }

    /** Builds and adds a new item. */
    public fun add(block: B.() -> Unit) {
        items += build(newBuilder().apply(block))
    }

    public fun toList(): List<T> = items.toList()
}
