package com.fajarnuha.kson

/** Generates a typed JSON decoder, encoder, and JSON Schema for an interface. */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.RUNTIME)
public annotation class Kson

/** A typed decoder generated by kson-ksp for a [Kson] interface. */
public interface KsonDecoder<out T> {
    /** The draft 2020-12 JSON Schema of [T]. */
    public val schema: JsonObject

    public fun decode(value: JsonValue): T

    public fun decode(text: String): T = decode(Json.parse(text))
}

/** A typed encoder generated by kson-ksp for a [Kson] interface. Nullable properties are written as JSON `null`. */
public interface KsonEncoder<in T> {
    public fun encode(value: T): JsonObject
}
