package com.fajarnuha.kson

import kotlin.properties.ReadWriteProperty
import kotlin.reflect.KProperty

/**
 * Stores one property of a builder generated by kson-ksp for a [Kson] interface. Until the property is set,
 * reading it returns [default], or throws [IllegalStateException] when there is no default.
 * [owner] names the interface in error messages.
 */
public class KsonProperty<T>(
    private val owner: String,
    private val default: (() -> T)? = null,
) : ReadWriteProperty<Any?, T> {
    private var value: Any? = null
    private var isSet = false

    override fun getValue(thisRef: Any?, property: KProperty<*>): T {
        if (!isSet) {
            val default = checkNotNull(default) { "$owner.${property.name} is not set" }
            return default()
        }
        @Suppress("UNCHECKED_CAST")
        return value as T
    }

    override fun setValue(thisRef: Any?, property: KProperty<*>, value: T) {
        this.value = value
        isSet = true
    }
}

/** Collects the items of a `List` property in a builder generated by kson-ksp. */
@JsonDsl
public class KsonListBuilder<T, B>(
    private val newBuilder: () -> B,
    private val build: (B) -> T,
) {
    private val items = mutableListOf<T>()

    /** Adds an existing value. */
    public fun add(value: T) {
        items += value
    }

    /** Builds and adds a new item. */
    public fun add(block: B.() -> Unit) {
        items += build(newBuilder().apply(block))
    }

    public fun toList(): List<T> = items.toList()
}
